title: Anthony Badea
short_title: Anthony Badea
email: anthony.badea@cern.ch

one_liner: Studying the building blocks of nature
description: >
  I am interested in studying the higgs boson, inventing new machine learning based analysis techniques, and building microelectronics for fundamental physics. 
  I am a Research Associate at the [Enrico Fermi Institute](https://efi.uchicago.edu) through the [Schmidt AI in Science Fellowship](https://aiscience.uchicago.edu/fellows).
  I received my Ph.D. in physics from Harvard University in 2023 and dual B.S. in physics and mathematics from MIT in 2019.

news_byline: >
  Here are some articles about projects I'm involved in.

# collaboration:
#   byline: We are a community that fosters knowledge transfer of accelerated and real-time artificial intelligence applications to fundamental science. By joining the community, you agree to abide by our codes of conduct and policies of collaboration.

  

navbar:
  logo: /images/favicon.ico
  links:
    - name: Home
      link: "#home" # Note that for links to autoscroll to anchors on the main page, only the #anchor is needed (no preceding slash)
      autoscroll: true
    - name: News
      link: "#news"
      autoscroll: true
    - name: Papers/Talks
      link: "#projects"
      autoscroll: true
    - name: Outreach
      link: "#outreach"
      autoscroll: true
    # - name: Collaboration
    #   link: "#collaboration"
    #   autoscroll: true
    - name: Sponsors/Partners
      link: '#sponsors'
      autoscroll: true
    - name: Contact
      link: "mailto:anthony.badea@cern.ch"
      autoscroll: false

footer:
  links:
    - name: GitHub
      link: https://github.com/badeaa3


exclude: ["CNAME", "license.txt", "README.md"]
