title: Anthony Badea
short_title: Anthony Badea
email: badea@uchicago.edu

# one_liner: Studying the building blocks of nature
description: >
  Anthony Badea is a research fellow at the [Enrico Fermi Institute](https://efi.uchicago.edu), where he works on particle physics, nuclear physics, and emerging technologies.

  Previously, Anthony has conducted measurements in electron, proton, and nuclei collisions to study the properties of the strong force and the matter-antimatter asymmetry of the universe. He has also been heavily involved in deploying new detector and readout electronics for experiments.

  Anthony earned his Ph.D. in physics from Harvard University as a Prize Fellow and dual B.S. degrees in physics and mathematics from MIT. 

# I am interested in studying the higgs boson, inventing new machine learning based analysis techniques, and building microelectronics for fundamental physics. 

news_byline: >
  Here are some articles about projects I'm involved in.

# collaboration:
#   byline: We are a community that fosters knowledge transfer of accelerated and real-time artificial intelligence applications to fundamental science. By joining the community, you agree to abide by our codes of conduct and policies of collaboration.

  

navbar:
  # logo: /images/favicon.ico
  links:
    - name: About
      link: /about.html
      autoscroll: false
    - name: CV
      link: /cv.html
      autoscroll: false
    - name: Contact
      link: "mailto:badea@uchicago.edu"
      autoscroll: false

social:
  email: badea@uchicago.edu
  github: badeaa3
  linkedin: anthony-badea
  google_scholar: YOUR_SCHOLAR_ID
  twitter: YOUR_TWITTER
  mit: YOUR_MIT_PAGE

footer:
  title: Research Fellow, Enrico Fermi Institute

exclude: ["CNAME", "license.txt", "README.md"]
